### ISSUE TITLE
Enabling Rinkeby Testnet

### ISSUE THREAD

**Issue by Barukimang** [Wallet3/Wallet3-Mobile#1]
Hi,

Thanks for your app, it's great to let ppl interact with Crypto for the first time. Could you please enable Rinkeby Testnet on the app? In that way we can let ppl first experience tx's with test-crypto before using the real thing.

**Comment by UnsignedInt8** [comment]
Hi

Thanks for using this wallet.

You can visit https://chainlist.org to add EVM networks, just need to turn on "Testnets"..

![image](https://user-images.githubusercontent.com/15274326/164863550-59ee94f5-3ac5-41f1-b912-ad5120bb2b55.png)

**Comment by Barukimang** [comment]
Hi @UnsignedInt8 Thanks for the answer. So if I understand it right flow would be:

1. Open Wallet3 Mobile app
2. Open Web3 browser
3. Surf to chainlist.org
4. Find Rinkeby
5. Connect wallet

Only #5 is failing, cannot Connect wallet. Should I do it differently?

**Comment by Barukimang** [comment]
For some reason it did work using chainlist.wtf ! Any idea why chainlist.org didn't work?

**Comment by UnsignedInt8** [comment]
How about this site: https://chainlist.defillama.com ?

**Comment by UnsignedInt8** [comment]
> Hi @UnsignedInt8 Thanks for the answer. So if I understand it right flow would be:
> 
> 1. Open Wallet3 Mobile app
> 2. Open Web3 browser
> 3. Surf to chainlist.org
> 4. Find Rinkeby
> 5. Connect wallet
> 
> Only #5 is failing, cannot Connect wallet. Should I do it differently?


1. Open Wallet3 Mobile app
2. Open Web3 browser
3. Surf to chainlist.org
4. Connect wallet. 
![image](https://user-images.githubusercontent.com/15274326/164953661-208c79c4-8a76-4d91-af79-62ee87620413.png)

5. Turn on "Testnet", find Rinkeby and tap "Add to Metamask"

![image](https://user-images.githubusercontent.com/15274326/164953689-11d6775a-fbfe-4f3c-9d1a-18ac5b86e5f6.png)

**Comment by UnsignedInt8** [comment]
Please do not add Rinkeby network from Chainlist.org. Chainlist.org has some bugs on testnets

**Comment by Barukimang** [comment]
Thanks for this @UnsignedInt8, managed with defilama
