### ISSUE TITLE
Support for Test Networks on M1 macbook pro app

### ISSUE THREAD

**Issue by naval200** [Wallet3/Wallet3-Mobile#3]
I tried to look up ropsten on Wallet3, but did not find it. I am using the latest desktop app on my M1 pro Macbook.

**Comment by baryon** [comment]
Yes, Just type "chainlist" from web3 browser, search network's name, press "connect" then "add" button.
a demo video for adding network
https://twitter.com/Wallet3_io/status/1570705202025725953?s=20&t=sG9TPTDg23RHpaN-Swv3ZA

**Comment by naval200** [comment]
We can close this issue or leave it open for the next person to come and find help. The number of upvotes can signify if there could be a possible UX improvement or updates to FAQ.
