### ISSUE TITLE
File configs/erc4337.config.ts not found

### ISSUE THREAD

**Issue by yl** [Wallet3/Wallet3-Mobile#6]
git commit: 
v4.1.2
Latest tag at this moment.

error:
iOS Bundling failed 2952ms
Unable to resolve "../configs/erc4337.config" from "common/Networks.ts"

**Comment by dp77** [comment]
@yl you found any solution?I'm getting this same error

**Comment by yl** [comment]
I think this may not be a real open source project.

**Comment by baryon** [comment]
The configuration file is not included in the source code. 

**Note** that this project is not a free open-source project and does not have any open-source License. The code here is for security audit purposes only. Any unauthorized use of the code is illegal unless official paid authorization is obtained.
